name: Deploy MemoJS Server to Elastic Beanstalk

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to Elastic Beanstalk
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python (for EB CLI)
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install AWS Elastic Beanstalk CLI
        run: |
          pip install awsebcli

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: your-aws-region  # e.g., us-east-1

      - name: Deploy to Elastic Beanstalk
        working-directory: ./server  # Adjust if your backend lives elsewhere
        run: |
          eb init memojs --platform node.js --region your-aws-region
          eb use your-env-name
          eb deploy
